### PR TITLE
little improvements

### PR DESCRIPTION
**Pull request by canewadar123**
Added the basic spells to Blackfuse and the shredder.

### CODE REVIEW

**Comment by cybrann** [comment]
If it's not complete script I cannot merge it because I have my codestyle and it will take too long to correct this ti mine so it's easier for me to do it by myself from scratch

**Comment by cooler-SAI** [comment]
@canewadar123 , may be you wanna plan your scripts fixes with @cybrann ? we need all help but it must be usefull

**Comment by cybrann** [comment]
@canewadar123 maybe you could do scripts for cata dungeons/raids?

**Comment by canewadar123** [comment]
which?

**Comment by cybrann** [comment]
Test some see which ones are broken

**Pull request closed without merging**
